# Generated by Django 4.2.16 on 2024-09-26 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='homepage.clients', verbose_name='Клиент-реферал')),
                ('referred_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_of', to='homepage.clients', verbose_name='Реферал')),
            ],
            options={
                'verbose_name': 'реферал',
                'verbose_name_plural': 'Рефералы',
            },
        ),
    ]
