# Generated by Django 4.2.16 on 2024-09-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_clients_referral_delete_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='number_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_clients', to='homepage.clients', verbose_name='Кто пригласил'),
        ),
    ]
