# Generated by Django 4.2.16 on 2024-09-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_clients_number_phone_alter_clients_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='deposit',
            field=models.IntegerField(default=0, verbose_name='Депозит'),
        ),
    ]
