# Generated by Django 4.2.16 on 2024-10-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0006_clients_deposit'),
        ('treners', '0006_remove_treners_specialties'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время тренировки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='homepage.clients')),
                ('trener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='treners.treners')),
            ],
            options={
                'unique_together': {('trener', 'date_time')},
            },
        ),
    ]
