# Generated by Django 4.2.16 on 2024-10-16 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sign_for_training", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingsessions",
            name="client",
        ),
        migrations.AddField(
            model_name="trainingsessions",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
    ]
