# Generated by Django 4.2.16 on 2024-09-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0005_clients_number_phone_alter_clients_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название специализации')),
            ],
            options={
                'verbose_name': 'специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Treners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='День рождения тренера')),
                ('number_phone', models.CharField(blank=True, max_length=50, verbose_name='Номер телефона')),
                ('specialties', models.ManyToManyField(related_name='trainers', to='treners.specialty', verbose_name='Специализации')),
            ],
            options={
                'verbose_name': 'тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='ClientTrainerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_relationships', to='homepage.clients', verbose_name='Клиент')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_relationships', to='treners.treners', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'связь между клиентом и тренером',
                'verbose_name_plural': 'Связи между клиентами и тренерами',
            },
        ),
    ]
