# Generated by Django 4.2.16 on 2024-09-27 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttrainerrelationship',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treners.specialty', verbose_name='Специализация'),
        ),
    ]
