# Generated by Django 4.2.16 on 2024-09-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treners', '0003_clienttrainerrelationship_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttrainerrelationship',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treners.specialty', verbose_name='Направление тренировок'),
        ),
    ]
