# Generated by Django 4.2.16 on 2024-09-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treners', '0004_alter_clienttrainerrelationship_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='price_eight_time',
            field=models.IntegerField(default=4000, verbose_name='Абонемент на 8 занятий'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='price_four_time',
            field=models.IntegerField(default=2200, verbose_name='Абонемент на 4 занятия'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='price_one_time',
            field=models.IntegerField(default=600, verbose_name='Стоимость одной тренировки'),
        ),
    ]
