# Generated by Django 4.2.16 on 2024-10-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treners', '0005_specialty_price_eight_time_specialty_price_four_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treners',
            name='specialties',
        ),
    ]
